openmaraude/APITaxi

APITaxi/models/hail.py
APITaxi/utils/make_model.py
APITaxi/views/hail.py
migrations/versions/b0eeeeb2671_operateur_id_is_now_a_foreign_key.py

Avec un gros hack degueu à enlever dans make_model

Show user login in hail's operator

---

APITaxi/__init__.py
APITaxi/default_settings.py
APITaxi/models/security.py
tests/hail_tests.py

Also it fixes the bug of hails

Introduce prod environment in conf

---

APITaxi/api/taxi.py
APITaxi/models/taxis.py
tests/taxis_tests.py

We will write tests when #134 is merged.

Fix is free

---

APITaxi/__init__.py
APITaxi/api/taxi.py
APITaxi/backoffice/ads.py
APITaxi/commands/__init__.py
APITaxi/commands/load_zupc.py
APITaxi/forms/administrative.py
APITaxi/index_zupc.py
APITaxi/models/administrative.py
APITaxi/models/taxis.py
README.md
migrations/versions/2e65dbaa935_change_shape_type_add_parent_and_insee.py
migrations/versions/450554023cb2_add_zupc_to_ads.py
requirements.txt
tests/ads_tests.py
tests/fake_data.py
tests/hail_tests.py
tests/skeleton.py
tests/taxis_tests.py

You need this file http://export.openstreetmap.fr/contours-administratifs/ and import it in a postgres/postgis db.
Then ask me for the geojson file of the ZUPC, and you'll be able to load it into the system!

Filter by zupc

---

migrations/versions/53c6b52778a7_add_declined_by_customer.py
tests/hail_tests.py

#157 needs to be merge before this one.

Add declined customer to db

---

APITaxi/models/taxis.py

Reverts openmaraude/APITaxi#194

Revert "Use only db.Column"

---

APITaxi/api/hail.py

Check for operator before checking is_free

---

APITaxi/api/hail.py
APITaxi/api/taxi.py
APITaxi/backoffice/ads.py
APITaxi/backoffice/drivers.py
APITaxi/backoffice/profile.py
APITaxi/backoffice/vehicle.py
APITaxi/models/hail.py
APITaxi/models/taxis.py
APITaxi/utils/cache_refresh.py
migrations/versions/1f76b661f96_add_hail_taxi_relation.py
tests/hail_tests.py

Taxi status' updates are now synchronize with hail updates

Change taxi status update

---

APITaxi/backoffice/__init__.py
scripts/celerybeat
scripts/celeryd
scripts/conf_example

Add script example

---

APITaxi/commands/load_zupc.py

With the new deployment script we don't need the first part anymore.

Adapt ZUPC script

---

APITaxi/__init__.py

We need to use redis to be able to dismiss a cache in any process

Use configuration to init cache

---

APITaxi/utils/caching.py
APITaxi/utils/mixins.py

Reverts openmaraude/APITaxi#307

Revert "temporary cache deactivation"

---

APITaxi/__init__.py
APITaxi/utils/caching.py

Reverts openmaraude/APITaxi#306

Revert "Flush after commit"

---

APITaxi/commands/__init__.py
APITaxi/commands/load_zupc.py

You need a geojson file of the airport you want to add
You can use as :
manage.py add_airport_zupc path_to_geojson insee

Add add_airport_zupc command

---

APITaxi/api/hail.py
APITaxi/tasks/send_request_operator.py

With this we can use memory cache for users in flask, hence have better
performances.

Do not call operateur in send_hail

---

APITaxi/api/taxi.py
APITaxi/models/taxis.py

Dict wasn't behaving correctly because of mutable things ...

Make a pseudo cache class

---

APITaxi/backoffice/vehicle.py

We have a vehicle_id when we post a description

Fix a bug in vehicle

---

APITaxi/api/taxi.py

I think we can optimize it.
It will be done later.

Add count parameter in GET /taxis/?lat&lon

---

APITaxi/__init__.py
APITaxi/api/taxi.py
APITaxi/utils/caching.py

Reverts openmaraude/APITaxi#382

Revert "Fix not available"

---

APITaxi/api/hail.py
APITaxi/models/hail.py
APITaxi/utils/mixins.py
tests/hail_tests.py

We store each datetime of hail status change

Add hail history field

---

APITaxi/api/hail.py

With this fix we'll neeed a custom dashboard to read the zupc.

Fix bug on posting hail to influx

---

APITaxi/__init__.py
APITaxi/api/taxi.py
APITaxi/default_settings.py
requirements.txt

We need to modify configuration files for this one

Add cache for ZUPC in GET /taxis/

---

APITaxi/api/zupc.py

Add zupc/<int:zupc_id>/_show_temp_geojson view

---

APITaxi/commands/__init__.py
APITaxi/commands/import_zupc.py

It can be launch with manage.py import_zupc
It will download contours from OSM, import it in a temporary table.
Then it will read /tmp/zupc directory. This directory can have one
directory per ZUPC, in each of it reads the content of *.list files,
each line of these files has to be a INSEE code, it will join every
insee of these files.
This is the begining, we still need to import geojson, and then merge the result in ZUPC table

Add command import_zupc

---

APITaxi/commands/import_zupc.py

We just need to add ZUPC with special names

Merge zones.

---

requirements.txt
tests/hail_tests.py

You can now go from received to received_by_taxi
If you go from received_by_taxi to received_by_operator, it won't be
overwritten

Accept new sequence of hail statuses

---

APITaxi/api/taxi.py
APITaxi/default_settings.py

We avoid to have a celery periodic task

Check data freshness on request

---

APITaxi/api/taxi.py

Try to fix a max_distance bug

---

APITaxi/commands/import_zupc.py

several things were not working anymore

Fix import_zupc

---

requirements.txt

RequestParser was not imported

Fix GET /hails/

---

APITaxi/api/ads.py

This was buggy and couldn't be used.
No one told us it was not working, so no one is using it.

Remove endpoint GET /ads/

---

APITaxi/descriptors/taxi.py
tests/taxis_tests.py

Will be unmerge at some point.
We let our partner correct some mistakes.

No check id taxi

---

APITaxi/descriptors/taxi.py
tests/taxis_tests.py

Reverts openmaraude/APITaxi#606
This was not the error, we want to check this actually.

Revert "No check id taxi"

---

.circleci/config.yml
.dockerignore
Dockerfile

Create Dockerfile to run the application in production with uwsgi-emperor.
Update circleci to push the docker image when a tag is pushed.

Publish docker image on git tag

---

APITaxi/api/taxi.py
tests/skeleton.py
tests/taxis_tests.py

This is an attempt to make this function understandable

Refacto of Taxis.get

---

tests/hail_tests.py
tests/skeleton.py

This is useful to run test with APITaxi_devel

Make hail endpoint configurable for test and add pg_isready command

---

APITaxi2/influx_backend.py
APITaxi2/tests/test_tasks.py

A bit fragile, should better order the queries.

tests: cover stats

---

APITaxi2/schemas.py
APITaxi2/views/ads.py
APITaxi2/views/taxis.py

And not just a cryptic INSEE code.
XXX but I'm sure it can be done better.

WIP add town name to the list of taxis on the console

---

APITaxi2/tests/test_taxis.py
APITaxi2/views/taxis.py

As the added comments state, Taxi.added_by is not the right filter.

fix operator searching a taxi also connected to other operators

---

APITaxi2/views/geotaxi.py

I couldn't keep just fetching the IDs:
sqlalchemy.exc.ArgumentError: Query has only expression-based entities, which do not apply to relationship property "Taxi.vehicle"

geotaxi: same fix for taxis registered to several operators

---

APITaxi2/commands/clean_db.py

Then print detailed blaming of operators.
This reverts commit f589e168d5ef34523636e8890496f77678f66ad6.

clean_db: turn into a read-only check script

---

APITaxi_models2/migrations/versions/20210907_08:37:05_50f5b6fadda8_shorter_insee_column.py
APITaxi_models2/zupc.py

TODO Alembic doesn't see the migration.

models: make INSEE more compact
